### ISSUE TITLE
ImportError: cannot import name 'Alphabet' from 'Bio.Seq'

### ISSUE THREAD

**Issue by ne1al** [kblin/merge-gbk-records#1]
I am trying to merge multiple gbk files into one file and I received the below error:
**The Code**
`merge-gbk-records NODE_2.gbk NODE_8.gbk NODE_13.gbk NODE_23.gbk NODE_32.gbk NODE_39.gbk NODE_42.gbk --length 5 > merged.gbk`
**The Error**
```
Traceback (most recent call last):
  File "/Users/anaconda3/bin/merge-gbk-records", line 5, in <module>
    from merge_gbk_records.__main__ import main
  File "/Users/anaconda3/lib/python3.8/site-packages/merge_gbk_records/__main__.py", line 3, in <module>
    from Bio.Seq import Seq, UnknownSeq, Alphabet
ImportError: cannot import name 'Alphabet' from 'Bio.Seq' (/Users/anaconda3/lib/python3.8/site-packages/Bio/Seq.py)
```
Any advice?

**Comment by Ainsleydmb** [comment]
Hello, 

I am having the same problem. I found this information here - https://biopython.org/wiki/Alphabet. It didn't allow me to fix this error but good to understand (ish) the issue.

**Comment by ne1al** [comment]
@Ainsleydmb I think it has been a while since they update it here

**Comment by kblin** [comment]
As a quick fix, you could downgrade the version of Biopython you're using. Since that change is from 1.78, installing biopython 1.77 should fix things.
If you installed merge-gbk-records via pip, you can run
`pip install biopython==1.77`
to force version 1.77 instead of a newer version.

**Comment by kblin** [comment]
Ah, I see I did fix that three months ago, I just forgot to create a new release. Sorry about that.

**Comment by kblin** [comment]
I've pushed the 0.1.2 release onto pypi, install it using
`pip install -U merge-gbk-records`

**Comment by Ainsleydmb** [comment]
Amazing, thanks! That all works now
